/*
 * Copyright (c) 2015, tibbitts
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package org.puyallupfamilyhistorycenter.service.models;

import com.google.gson.Gson;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 * @author tibbitts
 */
public class PersonTempleTest {

    String responseWithReadyOrdinances = "{\n"
            + "    \"status\": \"OK\",\n"
            + "    \"statusText\": null,\n"
            + "    \"data\": {\n"
            + "        \"id\": \"LJP7-JNK\",\n"
            + "        \"name\": \"Arthur G Ellis\",\n"
            + "        \"givenName\": \"Arthur G\",\n"
            + "        \"familyName\": \"Ellis\",\n"
            + "        \"nameFormScript\": null,\n"
            + "        \"lifespan\": \"1876-Deceased\",\n"
            + "        \"gender\": \"Male\",\n"
            + "        \"baptism\": {\n"
            + "            \"type\": \"Baptism\",\n"
            + "            \"status\": \"Completed\",\n"
            + "            \"whyNotQualifying\": [\n"
            + "                \"This ordinance is completed.\"\n"
            + "            ],\n"
            + "            \"statusText\": \"Completed\",\n"
            + "            \"hoverText\": \"Baptism completed at Seattle Washington Temple on 28 October 2014.\",\n"
            + "            \"bornInCovenant\": false,\n"
            + "            \"owner\": null,\n"
            + "            \"ownerName\": null,\n"
            + "            \"assignedToTemple\": false,\n"
            + "            \"canAssign\": false,\n"
            + "            \"canTransfer\": false,\n"
            + "            \"canUnreserve\": false,\n"
            + "            \"reserve\": false,\n"
            + "            \"canPrint\": false,\n"
            + "            \"reservedDate\": null,\n"
            + "            \"comparableReservedDate\": null,\n"
            + "            \"lastModifiedDate\": null,\n"
            + "            \"comparableLastModifiedDate\": null,\n"
            + "            \"completedDate\": \"28 October 2014\",\n"
            + "            \"completedPlace\": \"Seattle Washington Temple\",\n"
            + "            \"relationships\": {\n"
            + "                \"fatherId\": null,\n"
            + "                \"fatherName\": null,\n"
            + "                \"motherId\": null,\n"
            + "                \"motherName\": null,\n"
            + "                \"spouseId\": null,\n"
            + "                \"spouseName\": null,\n"
            + "                \"spouseGender\": null,\n"
            + "                \"spouseLifeSpan\": null,\n"
            + "                \"fatherLifeSpan\": null,\n"
            + "                \"motherLifeSpan\": null\n"
            + "            }\n"
            + "        },\n"
            + "        \"confirmation\": {\n"
            + "            \"type\": \"Confirmation\",\n"
            + "            \"status\": \"Completed\",\n"
            + "            \"whyNotQualifying\": [\n"
            + "                \"This ordinance is completed.\"\n"
            + "            ],\n"
            + "            \"statusText\": \"Completed\",\n"
            + "            \"hoverText\": \"Confirmation completed at Twin Falls Idaho Temple on 6 November 2014.\",\n"
            + "            \"bornInCovenant\": false,\n"
            + "            \"owner\": null,\n"
            + "            \"ownerName\": null,\n"
            + "            \"assignedToTemple\": false,\n"
            + "            \"canAssign\": false,\n"
            + "            \"canTransfer\": false,\n"
            + "            \"canUnreserve\": false,\n"
            + "            \"reserve\": false,\n"
            + "            \"canPrint\": false,\n"
            + "            \"reservedDate\": null,\n"
            + "            \"comparableReservedDate\": null,\n"
            + "            \"lastModifiedDate\": null,\n"
            + "            \"comparableLastModifiedDate\": null,\n"
            + "            \"completedDate\": \"6 November 2014\",\n"
            + "            \"completedPlace\": \"Twin Falls Idaho Temple\",\n"
            + "            \"relationships\": {\n"
            + "                \"fatherId\": null,\n"
            + "                \"fatherName\": null,\n"
            + "                \"motherId\": null,\n"
            + "                \"motherName\": null,\n"
            + "                \"spouseId\": null,\n"
            + "                \"spouseName\": null,\n"
            + "                \"spouseGender\": null,\n"
            + "                \"spouseLifeSpan\": null,\n"
            + "                \"fatherLifeSpan\": null,\n"
            + "                \"motherLifeSpan\": null\n"
            + "            }\n"
            + "        },\n"
            + "        \"initiatory\": {\n"
            + "            \"type\": \"Initiatory\",\n"
            + "            \"status\": \"Completed\",\n"
            + "            \"whyNotQualifying\": [\n"
            + "                \"This ordinance is completed.\"\n"
            + "            ],\n"
            + "            \"statusText\": \"Completed\",\n"
            + "            \"hoverText\": \"Initiatory completed at Seattle Washington Temple on 21 November 2014.\",\n"
            + "            \"bornInCovenant\": false,\n"
            + "            \"owner\": null,\n"
            + "            \"ownerName\": null,\n"
            + "            \"assignedToTemple\": false,\n"
            + "            \"canAssign\": false,\n"
            + "            \"canTransfer\": false,\n"
            + "            \"canUnreserve\": false,\n"
            + "            \"reserve\": false,\n"
            + "            \"canPrint\": false,\n"
            + "            \"reservedDate\": null,\n"
            + "            \"comparableReservedDate\": null,\n"
            + "            \"lastModifiedDate\": null,\n"
            + "            \"comparableLastModifiedDate\": null,\n"
            + "            \"completedDate\": \"21 November 2014\",\n"
            + "            \"completedPlace\": \"Seattle Washington Temple\",\n"
            + "            \"relationships\": {\n"
            + "                \"fatherId\": null,\n"
            + "                \"fatherName\": null,\n"
            + "                \"motherId\": null,\n"
            + "                \"motherName\": null,\n"
            + "                \"spouseId\": null,\n"
            + "                \"spouseName\": null,\n"
            + "                \"spouseGender\": null,\n"
            + "                \"spouseLifeSpan\": null,\n"
            + "                \"fatherLifeSpan\": null,\n"
            + "                \"motherLifeSpan\": null\n"
            + "            }\n"
            + "        },\n"
            + "        \"endowment\": {\n"
            + "            \"type\": \"Endowment\",\n"
            + "            \"status\": \"SharedInProgressNotPrinted\",\n"
            + "            \"whyNotQualifying\": [\n"
            + "                \"This person's record contains enough information for ordinances to be performed.\"\n"
            + "            ],\n"
            + "            \"statusText\": \"Shared Not Printed\",\n"
            + "            \"hoverText\": \"Endowment not printed. Shared with the temple system.\",\n"
            + "            \"bornInCovenant\": false,\n"
            + "            \"owner\": \"MMJ3-XMN\",\n"
            + "            \"ownerName\": \"Graham Tibbitts\",\n"
            + "            \"assignedToTemple\": true,\n"
            + "            \"canAssign\": true,\n"
            + "            \"canTransfer\": true,\n"
            + "            \"canUnreserve\": true,\n"
            + "            \"reserve\": true,\n"
            + "            \"canPrint\": false,\n"
            + "            \"reservedDate\": \"4 October 2014\",\n"
            + "            \"comparableReservedDate\": \"2014-10-05T00:35:12.118\",\n"
            + "            \"lastModifiedDate\": \"4 October 2014\",\n"
            + "            \"comparableLastModifiedDate\": \"2014-10-05T00:38:01.894\",\n"
            + "            \"completedDate\": null,\n"
            + "            \"completedPlace\": null,\n"
            + "            \"relationships\": {\n"
            + "                \"fatherId\": null,\n"
            + "                \"fatherName\": null,\n"
            + "                \"motherId\": null,\n"
            + "                \"motherName\": null,\n"
            + "                \"spouseId\": null,\n"
            + "                \"spouseName\": null,\n"
            + "                \"spouseGender\": null,\n"
            + "                \"spouseLifeSpan\": null,\n"
            + "                \"fatherLifeSpan\": null,\n"
            + "                \"motherLifeSpan\": null\n"
            + "            }\n"
            + "        },\n"
            + "        \"requiresPermission\": false,\n"
            + "        \"sealingsToParents\": [\n"
            + "            {\n"
            + "                \"type\": \"SealingToParents\",\n"
            + "                \"status\": \"SharedInProgressNotPrinted\",\n"
            + "                \"whyNotQualifying\": [\n"
            + "                    \"This person's record contains enough information for ordinances to be performed.\"\n"
            + "                ],\n"
            + "                \"statusText\": \"Shared Not Printed\",\n"
            + "                \"hoverText\": \"Sealing to Parents not printed. Shared with the temple system.\",\n"
            + "                \"bornInCovenant\": false,\n"
            + "                \"owner\": \"MMJ3-XMN\",\n"
            + "                \"ownerName\": \"Graham Tibbitts\",\n"
            + "                \"assignedToTemple\": true,\n"
            + "                \"canAssign\": true,\n"
            + "                \"canTransfer\": true,\n"
            + "                \"canUnreserve\": true,\n"
            + "                \"reserve\": true,\n"
            + "                \"canPrint\": false,\n"
            + "                \"reservedDate\": \"4 October 2014\",\n"
            + "                \"comparableReservedDate\": \"2014-10-05T00:35:12.118\",\n"
            + "                \"lastModifiedDate\": \"4 October 2014\",\n"
            + "                \"comparableLastModifiedDate\": \"2014-10-05T00:38:01.894\",\n"
            + "                \"completedDate\": null,\n"
            + "                \"completedPlace\": null,\n"
            + "                \"relationships\": {\n"
            + "                    \"fatherId\": \"LJP7-NBY\",\n"
            + "                    \"fatherName\": \"A L Ellis\",\n"
            + "                    \"motherId\": \"LJP7-J9B\",\n"
            + "                    \"motherName\": \"Mary A Pound\",\n"
            + "                    \"spouseId\": null,\n"
            + "                    \"spouseName\": null,\n"
            + "                    \"spouseGender\": null,\n"
            + "                    \"spouseLifeSpan\": null,\n"
            + "                    \"fatherLifeSpan\": null,\n"
            + "                    \"motherLifeSpan\": null\n"
            + "                }\n"
            + "            }\n"
            + "        ],\n"
            + "        \"sealingsToSpouses\": [\n"
            + "            {\n"
            + "                \"type\": \"SealingToSpouse\",\n"
            + "                \"status\": \"Ready\",\n"
            + "                \"whyNotQualifying\": [\n"
            + "                    \"This person's record contains enough information for ordinances to be performed.\"\n"
            + "                ],\n"
            + "                \"statusText\": \"Request\",\n"
            + "                \"hoverText\": \"Sealing to Spouse can be requested.\",\n"
            + "                \"bornInCovenant\": false,\n"
            + "                \"owner\": null,\n"
            + "                \"ownerName\": null,\n"
            + "                \"assignedToTemple\": false,\n"
            + "                \"canAssign\": false,\n"
            + "                \"canTransfer\": false,\n"
            + "                \"canUnreserve\": false,\n"
            + "                \"reserve\": false,\n"
            + "                \"canPrint\": false,\n"
            + "                \"reservedDate\": null,\n"
            + "                \"comparableReservedDate\": null,\n"
            + "                \"lastModifiedDate\": null,\n"
            + "                \"comparableLastModifiedDate\": null,\n"
            + "                \"completedDate\": null,\n"
            + "                \"completedPlace\": null,\n"
            + "                \"relationships\": {\n"
            + "                    \"fatherId\": null,\n"
            + "                    \"fatherName\": null,\n"
            + "                    \"motherId\": null,\n"
            + "                    \"motherName\": null,\n"
            + "                    \"spouseId\": \"LVDS-CN2\",\n"
            + "                    \"spouseName\": \"Georgia M Ellis\",\n"
            + "                    \"spouseGender\": \"Female\",\n"
            + "                    \"spouseLifeSpan\": null,\n"
            + "                    \"fatherLifeSpan\": null,\n"
            + "                    \"motherLifeSpan\": null\n"
            + "                }\n"
            + "            }\n"
            + "        ],\n"
            + "        \"hasPossibleDuplicates\": null\n"
            + "    },\n"
            + "    \"statuses\": null\n"
            + "}";

    String responseWithRequiresPermission = "{\n"
            + "    \"status\": \"OK\",\n"
            + "    \"statusText\": null,\n"
            + "    \"data\": {\n"
            + "        \"id\": \"LJP7-JNK\",\n"
            + "        \"name\": \"Arthur G Ellis\",\n"
            + "        \"givenName\": \"Arthur G\",\n"
            + "        \"familyName\": \"Ellis\",\n"
            + "        \"nameFormScript\": null,\n"
            + "        \"lifespan\": \"1876-Deceased\",\n"
            + "        \"gender\": \"Male\",\n"
            + "        \"baptism\": {\n"
            + "            \"type\": \"Baptism\",\n"
            + "            \"status\": \"Completed\",\n"
            + "            \"whyNotQualifying\": [\n"
            + "                \"This ordinance is completed.\"\n"
            + "            ],\n"
            + "            \"statusText\": \"Completed\",\n"
            + "            \"hoverText\": \"Baptism completed at Seattle Washington Temple on 28 October 2014.\",\n"
            + "            \"bornInCovenant\": false,\n"
            + "            \"owner\": null,\n"
            + "            \"ownerName\": null,\n"
            + "            \"assignedToTemple\": false,\n"
            + "            \"canAssign\": false,\n"
            + "            \"canTransfer\": false,\n"
            + "            \"canUnreserve\": false,\n"
            + "            \"reserve\": false,\n"
            + "            \"canPrint\": false,\n"
            + "            \"reservedDate\": null,\n"
            + "            \"comparableReservedDate\": null,\n"
            + "            \"lastModifiedDate\": null,\n"
            + "            \"comparableLastModifiedDate\": null,\n"
            + "            \"completedDate\": \"28 October 2014\",\n"
            + "            \"completedPlace\": \"Seattle Washington Temple\",\n"
            + "            \"relationships\": {\n"
            + "                \"fatherId\": null,\n"
            + "                \"fatherName\": null,\n"
            + "                \"motherId\": null,\n"
            + "                \"motherName\": null,\n"
            + "                \"spouseId\": null,\n"
            + "                \"spouseName\": null,\n"
            + "                \"spouseGender\": null,\n"
            + "                \"spouseLifeSpan\": null,\n"
            + "                \"fatherLifeSpan\": null,\n"
            + "                \"motherLifeSpan\": null\n"
            + "            }\n"
            + "        },\n"
            + "        \"confirmation\": {\n"
            + "            \"type\": \"Confirmation\",\n"
            + "            \"status\": \"Completed\",\n"
            + "            \"whyNotQualifying\": [\n"
            + "                \"This ordinance is completed.\"\n"
            + "            ],\n"
            + "            \"statusText\": \"Completed\",\n"
            + "            \"hoverText\": \"Confirmation completed at Twin Falls Idaho Temple on 6 November 2014.\",\n"
            + "            \"bornInCovenant\": false,\n"
            + "            \"owner\": null,\n"
            + "            \"ownerName\": null,\n"
            + "            \"assignedToTemple\": false,\n"
            + "            \"canAssign\": false,\n"
            + "            \"canTransfer\": false,\n"
            + "            \"canUnreserve\": false,\n"
            + "            \"reserve\": false,\n"
            + "            \"canPrint\": false,\n"
            + "            \"reservedDate\": null,\n"
            + "            \"comparableReservedDate\": null,\n"
            + "            \"lastModifiedDate\": null,\n"
            + "            \"comparableLastModifiedDate\": null,\n"
            + "            \"completedDate\": \"6 November 2014\",\n"
            + "            \"completedPlace\": \"Twin Falls Idaho Temple\",\n"
            + "            \"relationships\": {\n"
            + "                \"fatherId\": null,\n"
            + "                \"fatherName\": null,\n"
            + "                \"motherId\": null,\n"
            + "                \"motherName\": null,\n"
            + "                \"spouseId\": null,\n"
            + "                \"spouseName\": null,\n"
            + "                \"spouseGender\": null,\n"
            + "                \"spouseLifeSpan\": null,\n"
            + "                \"fatherLifeSpan\": null,\n"
            + "                \"motherLifeSpan\": null\n"
            + "            }\n"
            + "        },\n"
            + "        \"initiatory\": {\n"
            + "            \"type\": \"Initiatory\",\n"
            + "            \"status\": \"Completed\",\n"
            + "            \"whyNotQualifying\": [\n"
            + "                \"This ordinance is completed.\"\n"
            + "            ],\n"
            + "            \"statusText\": \"Completed\",\n"
            + "            \"hoverText\": \"Initiatory completed at Seattle Washington Temple on 21 November 2014.\",\n"
            + "            \"bornInCovenant\": false,\n"
            + "            \"owner\": null,\n"
            + "            \"ownerName\": null,\n"
            + "            \"assignedToTemple\": false,\n"
            + "            \"canAssign\": false,\n"
            + "            \"canTransfer\": false,\n"
            + "            \"canUnreserve\": false,\n"
            + "            \"reserve\": false,\n"
            + "            \"canPrint\": false,\n"
            + "            \"reservedDate\": null,\n"
            + "            \"comparableReservedDate\": null,\n"
            + "            \"lastModifiedDate\": null,\n"
            + "            \"comparableLastModifiedDate\": null,\n"
            + "            \"completedDate\": \"21 November 2014\",\n"
            + "            \"completedPlace\": \"Seattle Washington Temple\",\n"
            + "            \"relationships\": {\n"
            + "                \"fatherId\": null,\n"
            + "                \"fatherName\": null,\n"
            + "                \"motherId\": null,\n"
            + "                \"motherName\": null,\n"
            + "                \"spouseId\": null,\n"
            + "                \"spouseName\": null,\n"
            + "                \"spouseGender\": null,\n"
            + "                \"spouseLifeSpan\": null,\n"
            + "                \"fatherLifeSpan\": null,\n"
            + "                \"motherLifeSpan\": null\n"
            + "            }\n"
            + "        },\n"
            + "        \"endowment\": {\n"
            + "            \"type\": \"Endowment\",\n"
            + "            \"status\": \"SharedInProgressNotPrinted\",\n"
            + "            \"whyNotQualifying\": [\n"
            + "                \"This person's record contains enough information for ordinances to be performed.\"\n"
            + "            ],\n"
            + "            \"statusText\": \"Shared Not Printed\",\n"
            + "            \"hoverText\": \"Endowment not printed. Shared with the temple system.\",\n"
            + "            \"bornInCovenant\": false,\n"
            + "            \"owner\": \"MMJ3-XMN\",\n"
            + "            \"ownerName\": \"Graham Tibbitts\",\n"
            + "            \"assignedToTemple\": true,\n"
            + "            \"canAssign\": true,\n"
            + "            \"canTransfer\": true,\n"
            + "            \"canUnreserve\": true,\n"
            + "            \"reserve\": true,\n"
            + "            \"canPrint\": false,\n"
            + "            \"reservedDate\": \"4 October 2014\",\n"
            + "            \"comparableReservedDate\": \"2014-10-05T00:35:12.118\",\n"
            + "            \"lastModifiedDate\": \"4 October 2014\",\n"
            + "            \"comparableLastModifiedDate\": \"2014-10-05T00:38:01.894\",\n"
            + "            \"completedDate\": null,\n"
            + "            \"completedPlace\": null,\n"
            + "            \"relationships\": {\n"
            + "                \"fatherId\": null,\n"
            + "                \"fatherName\": null,\n"
            + "                \"motherId\": null,\n"
            + "                \"motherName\": null,\n"
            + "                \"spouseId\": null,\n"
            + "                \"spouseName\": null,\n"
            + "                \"spouseGender\": null,\n"
            + "                \"spouseLifeSpan\": null,\n"
            + "                \"fatherLifeSpan\": null,\n"
            + "                \"motherLifeSpan\": null\n"
            + "            }\n"
            + "        },\n"
            + "        \"requiresPermission\": true,\n"
            + "        \"sealingsToParents\": [\n"
            + "            {\n"
            + "                \"type\": \"SealingToParents\",\n"
            + "                \"status\": \"SharedInProgressNotPrinted\",\n"
            + "                \"whyNotQualifying\": [\n"
            + "                    \"This person's record contains enough information for ordinances to be performed.\"\n"
            + "                ],\n"
            + "                \"statusText\": \"Shared Not Printed\",\n"
            + "                \"hoverText\": \"Sealing to Parents not printed. Shared with the temple system.\",\n"
            + "                \"bornInCovenant\": false,\n"
            + "                \"owner\": \"MMJ3-XMN\",\n"
            + "                \"ownerName\": \"Graham Tibbitts\",\n"
            + "                \"assignedToTemple\": true,\n"
            + "                \"canAssign\": true,\n"
            + "                \"canTransfer\": true,\n"
            + "                \"canUnreserve\": true,\n"
            + "                \"reserve\": true,\n"
            + "                \"canPrint\": false,\n"
            + "                \"reservedDate\": \"4 October 2014\",\n"
            + "                \"comparableReservedDate\": \"2014-10-05T00:35:12.118\",\n"
            + "                \"lastModifiedDate\": \"4 October 2014\",\n"
            + "                \"comparableLastModifiedDate\": \"2014-10-05T00:38:01.894\",\n"
            + "                \"completedDate\": null,\n"
            + "                \"completedPlace\": null,\n"
            + "                \"relationships\": {\n"
            + "                    \"fatherId\": \"LJP7-NBY\",\n"
            + "                    \"fatherName\": \"A L Ellis\",\n"
            + "                    \"motherId\": \"LJP7-J9B\",\n"
            + "                    \"motherName\": \"Mary A Pound\",\n"
            + "                    \"spouseId\": null,\n"
            + "                    \"spouseName\": null,\n"
            + "                    \"spouseGender\": null,\n"
            + "                    \"spouseLifeSpan\": null,\n"
            + "                    \"fatherLifeSpan\": null,\n"
            + "                    \"motherLifeSpan\": null\n"
            + "                }\n"
            + "            }\n"
            + "        ],\n"
            + "        \"sealingsToSpouses\": [\n"
            + "            {\n"
            + "                \"type\": \"SealingToSpouse\",\n"
            + "                \"status\": \"Ready\",\n"
            + "                \"whyNotQualifying\": [\n"
            + "                    \"This person's record contains enough information for ordinances to be performed.\"\n"
            + "                ],\n"
            + "                \"statusText\": \"Request\",\n"
            + "                \"hoverText\": \"Sealing to Spouse can be requested.\",\n"
            + "                \"bornInCovenant\": false,\n"
            + "                \"owner\": null,\n"
            + "                \"ownerName\": null,\n"
            + "                \"assignedToTemple\": false,\n"
            + "                \"canAssign\": false,\n"
            + "                \"canTransfer\": false,\n"
            + "                \"canUnreserve\": false,\n"
            + "                \"reserve\": false,\n"
            + "                \"canPrint\": false,\n"
            + "                \"reservedDate\": null,\n"
            + "                \"comparableReservedDate\": null,\n"
            + "                \"lastModifiedDate\": null,\n"
            + "                \"comparableLastModifiedDate\": null,\n"
            + "                \"completedDate\": null,\n"
            + "                \"completedPlace\": null,\n"
            + "                \"relationships\": {\n"
            + "                    \"fatherId\": null,\n"
            + "                    \"fatherName\": null,\n"
            + "                    \"motherId\": null,\n"
            + "                    \"motherName\": null,\n"
            + "                    \"spouseId\": \"LVDS-CN2\",\n"
            + "                    \"spouseName\": \"Georgia M Ellis\",\n"
            + "                    \"spouseGender\": \"Female\",\n"
            + "                    \"spouseLifeSpan\": null,\n"
            + "                    \"fatherLifeSpan\": null,\n"
            + "                    \"motherLifeSpan\": null\n"
            + "                }\n"
            + "            }\n"
            + "        ],\n"
            + "        \"hasPossibleDuplicates\": null\n"
            + "    },\n"
            + "    \"statuses\": null\n"
            + "}";

    String responseWithClaimedOrdinances = "    {\n"
            + "        \"status\": \"OK\",\n"
            + "        \"statusText\": null,\n"
            + "        \"data\": {\n"
            + "            \"id\": \"LJP7-JNK\",\n"
            + "            \"name\": \"Arthur G Ellis\",\n"
            + "            \"givenName\": \"Arthur G\",\n"
            + "            \"familyName\": \"Ellis\",\n"
            + "            \"nameFormScript\": null,\n"
            + "            \"lifespan\": \"1876-Deceased\",\n"
            + "            \"gender\": \"Male\",\n"
            + "            \"baptism\": {\n"
            + "                \"type\": \"Baptism\",\n"
            + "                \"status\": \"Completed\",\n"
            + "                \"whyNotQualifying\": [\n"
            + "                    \"This ordinance is completed.\"\n"
            + "                ],\n"
            + "                \"statusText\": \"Completed\",\n"
            + "                \"hoverText\": \"Baptism completed at Seattle Washington Temple on 28 October 2014.\",\n"
            + "                \"bornInCovenant\": false,\n"
            + "                \"owner\": null,\n"
            + "                \"ownerName\": null,\n"
            + "                \"assignedToTemple\": false,\n"
            + "                \"canAssign\": false,\n"
            + "                \"canTransfer\": false,\n"
            + "                \"canUnreserve\": false,\n"
            + "                \"reserve\": false,\n"
            + "                \"canPrint\": false,\n"
            + "                \"reservedDate\": null,\n"
            + "                \"comparableReservedDate\": null,\n"
            + "                \"lastModifiedDate\": null,\n"
            + "                \"comparableLastModifiedDate\": null,\n"
            + "                \"completedDate\": \"28 October 2014\",\n"
            + "                \"completedPlace\": \"Seattle Washington Temple\",\n"
            + "                \"relationships\": {\n"
            + "                    \"fatherId\": null,\n"
            + "                    \"fatherName\": null,\n"
            + "                    \"motherId\": null,\n"
            + "                    \"motherName\": null,\n"
            + "                    \"spouseId\": null,\n"
            + "                    \"spouseName\": null,\n"
            + "                    \"spouseGender\": null,\n"
            + "                    \"spouseLifeSpan\": null,\n"
            + "                    \"fatherLifeSpan\": null,\n"
            + "                    \"motherLifeSpan\": null\n"
            + "                }\n"
            + "            },\n"
            + "            \"confirmation\": {\n"
            + "                \"type\": \"Confirmation\",\n"
            + "                \"status\": \"Completed\",\n"
            + "                \"whyNotQualifying\": [\n"
            + "                    \"This ordinance is completed.\"\n"
            + "                ],\n"
            + "                \"statusText\": \"Completed\",\n"
            + "                \"hoverText\": \"Confirmation completed at Twin Falls Idaho Temple on 6 November 2014.\",\n"
            + "                \"bornInCovenant\": false,\n"
            + "                \"owner\": null,\n"
            + "                \"ownerName\": null,\n"
            + "                \"assignedToTemple\": false,\n"
            + "                \"canAssign\": false,\n"
            + "                \"canTransfer\": false,\n"
            + "                \"canUnreserve\": false,\n"
            + "                \"reserve\": false,\n"
            + "                \"canPrint\": false,\n"
            + "                \"reservedDate\": null,\n"
            + "                \"comparableReservedDate\": null,\n"
            + "                \"lastModifiedDate\": null,\n"
            + "                \"comparableLastModifiedDate\": null,\n"
            + "                \"completedDate\": \"6 November 2014\",\n"
            + "                \"completedPlace\": \"Twin Falls Idaho Temple\",\n"
            + "                \"relationships\": {\n"
            + "                    \"fatherId\": null,\n"
            + "                    \"fatherName\": null,\n"
            + "                    \"motherId\": null,\n"
            + "                    \"motherName\": null,\n"
            + "                    \"spouseId\": null,\n"
            + "                    \"spouseName\": null,\n"
            + "                    \"spouseGender\": null,\n"
            + "                    \"spouseLifeSpan\": null,\n"
            + "                    \"fatherLifeSpan\": null,\n"
            + "                    \"motherLifeSpan\": null\n"
            + "                }\n"
            + "            },\n"
            + "            \"initiatory\": {\n"
            + "                \"type\": \"Initiatory\",\n"
            + "                \"status\": \"Completed\",\n"
            + "                \"whyNotQualifying\": [\n"
            + "                    \"This ordinance is completed.\"\n"
            + "                ],\n"
            + "                \"statusText\": \"Completed\",\n"
            + "                \"hoverText\": \"Initiatory completed at Seattle Washington Temple on 21 November 2014.\",\n"
            + "                \"bornInCovenant\": false,\n"
            + "                \"owner\": null,\n"
            + "                \"ownerName\": null,\n"
            + "                \"assignedToTemple\": false,\n"
            + "                \"canAssign\": false,\n"
            + "                \"canTransfer\": false,\n"
            + "                \"canUnreserve\": false,\n"
            + "                \"reserve\": false,\n"
            + "                \"canPrint\": false,\n"
            + "                \"reservedDate\": null,\n"
            + "                \"comparableReservedDate\": null,\n"
            + "                \"lastModifiedDate\": null,\n"
            + "                \"comparableLastModifiedDate\": null,\n"
            + "                \"completedDate\": \"21 November 2014\",\n"
            + "                \"completedPlace\": \"Seattle Washington Temple\",\n"
            + "                \"relationships\": {\n"
            + "                    \"fatherId\": null,\n"
            + "                    \"fatherName\": null,\n"
            + "                    \"motherId\": null,\n"
            + "                    \"motherName\": null,\n"
            + "                    \"spouseId\": null,\n"
            + "                    \"spouseName\": null,\n"
            + "                    \"spouseGender\": null,\n"
            + "                    \"spouseLifeSpan\": null,\n"
            + "                    \"fatherLifeSpan\": null,\n"
            + "                    \"motherLifeSpan\": null\n"
            + "                }\n"
            + "            },\n"
            + "            \"endowment\": {\n"
            + "                \"type\": \"Endowment\",\n"
            + "                \"status\": \"SharedInProgressNotPrinted\",\n"
            + "                \"whyNotQualifying\": [\n"
            + "                    \"This person's record contains enough information for ordinances to be performed.\"\n"
            + "                ],\n"
            + "                \"statusText\": \"Shared Not Printed\",\n"
            + "                \"hoverText\": \"Endowment not printed. Shared with the temple system.\",\n"
            + "                \"bornInCovenant\": false,\n"
            + "                \"owner\": \"MMJ3-XMN\",\n"
            + "                \"ownerName\": \"Graham Tibbitts\",\n"
            + "                \"assignedToTemple\": true,\n"
            + "                \"canAssign\": true,\n"
            + "                \"canTransfer\": true,\n"
            + "                \"canUnreserve\": true,\n"
            + "                \"reserve\": true,\n"
            + "                \"canPrint\": false,\n"
            + "                \"reservedDate\": \"4 October 2014\",\n"
            + "                \"comparableReservedDate\": \"2014-10-05T00:35:12.118\",\n"
            + "                \"lastModifiedDate\": \"4 October 2014\",\n"
            + "                \"comparableLastModifiedDate\": \"2014-10-05T00:38:01.894\",\n"
            + "                \"completedDate\": null,\n"
            + "                \"completedPlace\": null,\n"
            + "                \"relationships\": {\n"
            + "                    \"fatherId\": null,\n"
            + "                    \"fatherName\": null,\n"
            + "                    \"motherId\": null,\n"
            + "                    \"motherName\": null,\n"
            + "                    \"spouseId\": null,\n"
            + "                    \"spouseName\": null,\n"
            + "                    \"spouseGender\": null,\n"
            + "                    \"spouseLifeSpan\": null,\n"
            + "                    \"fatherLifeSpan\": null,\n"
            + "                    \"motherLifeSpan\": null\n"
            + "                }\n"
            + "            },\n"
            + "            \"requiresPermission\": false,\n"
            + "            \"sealingsToParents\": [\n"
            + "                {\n"
            + "                    \"type\": \"SealingToParents\",\n"
            + "                    \"status\": \"SharedInProgressNotPrinted\",\n"
            + "                    \"whyNotQualifying\": [\n"
            + "                        \"This person's record contains enough information for ordinances to be performed.\"\n"
            + "                    ],\n"
            + "                    \"statusText\": \"Shared Not Printed\",\n"
            + "                    \"hoverText\": \"Sealing to Parents not printed. Shared with the temple system.\",\n"
            + "                    \"bornInCovenant\": false,\n"
            + "                    \"owner\": \"MMJ3-XMN\",\n"
            + "                    \"ownerName\": \"Graham Tibbitts\",\n"
            + "                    \"assignedToTemple\": true,\n"
            + "                    \"canAssign\": true,\n"
            + "                    \"canTransfer\": true,\n"
            + "                    \"canUnreserve\": true,\n"
            + "                    \"reserve\": true,\n"
            + "                    \"canPrint\": false,\n"
            + "                    \"reservedDate\": \"4 October 2014\",\n"
            + "                    \"comparableReservedDate\": \"2014-10-05T00:35:12.118\",\n"
            + "                    \"lastModifiedDate\": \"4 October 2014\",\n"
            + "                    \"comparableLastModifiedDate\": \"2014-10-05T00:38:01.894\",\n"
            + "                    \"completedDate\": null,\n"
            + "                    \"completedPlace\": null,\n"
            + "                    \"relationships\": {\n"
            + "                        \"fatherId\": \"LJP7-NBY\",\n"
            + "                        \"fatherName\": \"A L Ellis\",\n"
            + "                        \"motherId\": \"LJP7-J9B\",\n"
            + "                        \"motherName\": \"Mary A Pound\",\n"
            + "                        \"spouseId\": null,\n"
            + "                        \"spouseName\": null,\n"
            + "                        \"spouseGender\": null,\n"
            + "                        \"spouseLifeSpan\": null,\n"
            + "                        \"fatherLifeSpan\": null,\n"
            + "                        \"motherLifeSpan\": null\n"
            + "                    }\n"
            + "                }\n"
            + "            ],\n"
            + "            \"sealingsToSpouses\": [\n"
            + "                {\n"
            + "                    \"type\": \"SealingToSpouse\",\n"
            + "                    \"status\": \"SharedInProgressNotPrinted\",\n"
            + "                    \"whyNotQualifying\": [\n"
            + "                        \"This person's record contains enough information for ordinances to be performed.\"\n"
            + "                    ],\n"
            + "                    \"statusText\": \"Request\",\n"
            + "                    \"hoverText\": \"Sealing to Spouse can be requested.\",\n"
            + "                    \"bornInCovenant\": false,\n"
            + "                    \"owner\": null,\n"
            + "                    \"ownerName\": null,\n"
            + "                    \"assignedToTemple\": false,\n"
            + "                    \"canAssign\": false,\n"
            + "                    \"canTransfer\": false,\n"
            + "                    \"canUnreserve\": false,\n"
            + "                    \"reserve\": false,\n"
            + "                    \"canPrint\": false,\n"
            + "                    \"reservedDate\": null,\n"
            + "                    \"comparableReservedDate\": null,\n"
            + "                    \"lastModifiedDate\": null,\n"
            + "                    \"comparableLastModifiedDate\": null,\n"
            + "                    \"completedDate\": null,\n"
            + "                    \"completedPlace\": null,\n"
            + "                    \"relationships\": {\n"
            + "                        \"fatherId\": null,\n"
            + "                        \"fatherName\": null,\n"
            + "                        \"motherId\": null,\n"
            + "                        \"motherName\": null,\n"
            + "                        \"spouseId\": \"LVDS-CN2\",\n"
            + "                        \"spouseName\": \"Georgia M Ellis\",\n"
            + "                        \"spouseGender\": \"Female\",\n"
            + "                        \"spouseLifeSpan\": null,\n"
            + "                        \"fatherLifeSpan\": null,\n"
            + "                        \"motherLifeSpan\": null\n"
            + "                    }\n"
            + "                }\n"
            + "            ],\n"
            + "            \"hasPossibleDuplicates\": null\n"
            + "        },\n"
            + "        \"statuses\": null\n"
            + "    }";

    String responseWithCompletedOrdinances = "{\n"
            + "    \"status\": \"OK\",\n"
            + "    \"statusText\": null,\n"
            + "    \"data\": {\n"
            + "        \"id\": \"KCS5-8CD\",\n"
            + "        \"name\": \"George Washington &quot;GW&quot; Neely Nealy\",\n"
            + "        \"givenName\": \"George Washington &quot;GW&quot;\",\n"
            + "        \"familyName\": \"Neely Nealy\",\n"
            + "        \"nameFormScript\": null,\n"
            + "        \"lifespan\": \"1835-Deceased\",\n"
            + "        \"gender\": \"Male\",\n"
            + "        \"baptism\": {\n"
            + "            \"type\": \"Baptism\",\n"
            + "            \"status\": \"Completed\",\n"
            + "            \"whyNotQualifying\": [\n"
            + "                \"This ordinance is completed.\"\n"
            + "            ],\n"
            + "            \"statusText\": \"Completed\",\n"
            + "            \"hoverText\": \"Baptism completed at Chicago Illinois Temple on 1 July 1995.\",\n"
            + "            \"bornInCovenant\": false,\n"
            + "            \"owner\": null,\n"
            + "            \"ownerName\": null,\n"
            + "            \"assignedToTemple\": false,\n"
            + "            \"canAssign\": false,\n"
            + "            \"canTransfer\": false,\n"
            + "            \"canUnreserve\": false,\n"
            + "            \"reserve\": false,\n"
            + "            \"canPrint\": false,\n"
            + "            \"reservedDate\": null,\n"
            + "            \"comparableReservedDate\": null,\n"
            + "            \"lastModifiedDate\": null,\n"
            + "            \"comparableLastModifiedDate\": null,\n"
            + "            \"completedDate\": \"1 July 1995\",\n"
            + "            \"completedPlace\": \"Chicago Illinois Temple\",\n"
            + "            \"relationships\": {\n"
            + "                \"fatherId\": null,\n"
            + "                \"fatherName\": null,\n"
            + "                \"motherId\": null,\n"
            + "                \"motherName\": null,\n"
            + "                \"spouseId\": null,\n"
            + "                \"spouseName\": null,\n"
            + "                \"spouseGender\": null,\n"
            + "                \"spouseLifeSpan\": null,\n"
            + "                \"fatherLifeSpan\": null,\n"
            + "                \"motherLifeSpan\": null\n"
            + "            }\n"
            + "        },\n"
            + "        \"confirmation\": {\n"
            + "            \"type\": \"Confirmation\",\n"
            + "            \"status\": \"Completed\",\n"
            + "            \"whyNotQualifying\": [\n"
            + "                \"This ordinance is completed.\"\n"
            + "            ],\n"
            + "            \"statusText\": \"Completed\",\n"
            + "            \"hoverText\": \"Confirmation completed at Ogden Utah Temple on 4 June 2005.\",\n"
            + "            \"bornInCovenant\": false,\n"
            + "            \"owner\": null,\n"
            + "            \"ownerName\": null,\n"
            + "            \"assignedToTemple\": false,\n"
            + "            \"canAssign\": false,\n"
            + "            \"canTransfer\": false,\n"
            + "            \"canUnreserve\": false,\n"
            + "            \"reserve\": false,\n"
            + "            \"canPrint\": false,\n"
            + "            \"reservedDate\": null,\n"
            + "            \"comparableReservedDate\": null,\n"
            + "            \"lastModifiedDate\": null,\n"
            + "            \"comparableLastModifiedDate\": null,\n"
            + "            \"completedDate\": \"4 June 2005\",\n"
            + "            \"completedPlace\": \"Ogden Utah Temple\",\n"
            + "            \"relationships\": {\n"
            + "                \"fatherId\": null,\n"
            + "                \"fatherName\": null,\n"
            + "                \"motherId\": null,\n"
            + "                \"motherName\": null,\n"
            + "                \"spouseId\": null,\n"
            + "                \"spouseName\": null,\n"
            + "                \"spouseGender\": null,\n"
            + "                \"spouseLifeSpan\": null,\n"
            + "                \"fatherLifeSpan\": null,\n"
            + "                \"motherLifeSpan\": null\n"
            + "            }\n"
            + "        },\n"
            + "        \"initiatory\": {\n"
            + "            \"type\": \"Initiatory\",\n"
            + "            \"status\": \"Completed\",\n"
            + "            \"whyNotQualifying\": [\n"
            + "                \"This ordinance is completed.\"\n"
            + "            ],\n"
            + "            \"statusText\": \"Completed\",\n"
            + "            \"hoverText\": \"Initiatory completed at Ogden Utah Temple on 22 September 2005.\",\n"
            + "            \"bornInCovenant\": false,\n"
            + "            \"owner\": null,\n"
            + "            \"ownerName\": null,\n"
            + "            \"assignedToTemple\": false,\n"
            + "            \"canAssign\": false,\n"
            + "            \"canTransfer\": false,\n"
            + "            \"canUnreserve\": false,\n"
            + "            \"reserve\": false,\n"
            + "            \"canPrint\": false,\n"
            + "            \"reservedDate\": null,\n"
            + "            \"comparableReservedDate\": null,\n"
            + "            \"lastModifiedDate\": null,\n"
            + "            \"comparableLastModifiedDate\": null,\n"
            + "            \"completedDate\": \"22 September 2005\",\n"
            + "            \"completedPlace\": \"Ogden Utah Temple\",\n"
            + "            \"relationships\": {\n"
            + "                \"fatherId\": null,\n"
            + "                \"fatherName\": null,\n"
            + "                \"motherId\": null,\n"
            + "                \"motherName\": null,\n"
            + "                \"spouseId\": null,\n"
            + "                \"spouseName\": null,\n"
            + "                \"spouseGender\": null,\n"
            + "                \"spouseLifeSpan\": null,\n"
            + "                \"fatherLifeSpan\": null,\n"
            + "                \"motherLifeSpan\": null\n"
            + "            }\n"
            + "        },\n"
            + "        \"endowment\": {\n"
            + "            \"type\": \"Endowment\",\n"
            + "            \"status\": \"Completed\",\n"
            + "            \"whyNotQualifying\": [\n"
            + "                \"This ordinance is completed.\"\n"
            + "            ],\n"
            + "            \"statusText\": \"Completed\",\n"
            + "            \"hoverText\": \"Endowment completed at Chicago Illinois Temple on 13 July 1995.\",\n"
            + "            \"bornInCovenant\": false,\n"
            + "            \"owner\": null,\n"
            + "            \"ownerName\": null,\n"
            + "            \"assignedToTemple\": false,\n"
            + "            \"canAssign\": false,\n"
            + "            \"canTransfer\": false,\n"
            + "            \"canUnreserve\": false,\n"
            + "            \"reserve\": false,\n"
            + "            \"canPrint\": false,\n"
            + "            \"reservedDate\": null,\n"
            + "            \"comparableReservedDate\": null,\n"
            + "            \"lastModifiedDate\": null,\n"
            + "            \"comparableLastModifiedDate\": null,\n"
            + "            \"completedDate\": \"13 July 1995\",\n"
            + "            \"completedPlace\": \"Chicago Illinois Temple\",\n"
            + "            \"relationships\": {\n"
            + "                \"fatherId\": null,\n"
            + "                \"fatherName\": null,\n"
            + "                \"motherId\": null,\n"
            + "                \"motherName\": null,\n"
            + "                \"spouseId\": null,\n"
            + "                \"spouseName\": null,\n"
            + "                \"spouseGender\": null,\n"
            + "                \"spouseLifeSpan\": null,\n"
            + "                \"fatherLifeSpan\": null,\n"
            + "                \"motherLifeSpan\": null\n"
            + "            }\n"
            + "        },\n"
            + "        \"requiresPermission\": false,\n"
            + "        \"sealingsToParents\": [\n"
            + "            {\n"
            + "                \"type\": \"SealingToParents\",\n"
            + "                \"status\": \"Completed\",\n"
            + "                \"whyNotQualifying\": [],\n"
            + "                \"statusText\": \"Completed\",\n"
            + "                \"hoverText\": \"Sealing to Parents completed at Ogden Utah Temple on 4 March 2006.\",\n"
            + "                \"bornInCovenant\": false,\n"
            + "                \"owner\": null,\n"
            + "                \"ownerName\": null,\n"
            + "                \"assignedToTemple\": false,\n"
            + "                \"canAssign\": false,\n"
            + "                \"canTransfer\": false,\n"
            + "                \"canUnreserve\": false,\n"
            + "                \"reserve\": false,\n"
            + "                \"canPrint\": false,\n"
            + "                \"reservedDate\": null,\n"
            + "                \"comparableReservedDate\": null,\n"
            + "                \"lastModifiedDate\": null,\n"
            + "                \"comparableLastModifiedDate\": null,\n"
            + "                \"completedDate\": \"4 March 2006\",\n"
            + "                \"completedPlace\": \"Ogden Utah Temple\",\n"
            + "                \"relationships\": {\n"
            + "                    \"fatherId\": null,\n"
            + "                    \"fatherName\": null,\n"
            + "                    \"motherId\": null,\n"
            + "                    \"motherName\": null,\n"
            + "                    \"spouseId\": null,\n"
            + "                    \"spouseName\": null,\n"
            + "                    \"spouseGender\": null,\n"
            + "                    \"spouseLifeSpan\": null,\n"
            + "                    \"fatherLifeSpan\": null,\n"
            + "                    \"motherLifeSpan\": null\n"
            + "                }\n"
            + "            },\n"
            + "            {\n"
            + "                \"type\": \"SealingToParents\",\n"
            + "                \"status\": \"Completed\",\n"
            + "                \"whyNotQualifying\": [\n"
            + "                    \"This ordinance is completed.\"\n"
            + "                ],\n"
            + "                \"statusText\": \"Completed\",\n"
            + "                \"hoverText\": \"Sealing to Parents completed at Billings Montana Temple on 19 February 2010.\",\n"
            + "                \"bornInCovenant\": false,\n"
            + "                \"owner\": null,\n"
            + "                \"ownerName\": null,\n"
            + "                \"assignedToTemple\": false,\n"
            + "                \"canAssign\": false,\n"
            + "                \"canTransfer\": false,\n"
            + "                \"canUnreserve\": false,\n"
            + "                \"reserve\": false,\n"
            + "                \"canPrint\": false,\n"
            + "                \"reservedDate\": null,\n"
            + "                \"comparableReservedDate\": null,\n"
            + "                \"lastModifiedDate\": null,\n"
            + "                \"comparableLastModifiedDate\": null,\n"
            + "                \"completedDate\": \"19 February 2010\",\n"
            + "                \"completedPlace\": \"Billings Montana Temple\",\n"
            + "                \"relationships\": {\n"
            + "                    \"fatherId\": \"KL1Q-B8S\",\n"
            + "                    \"fatherName\": \"George Neely\",\n"
            + "                    \"motherId\": \"KL1Q-BF9\",\n"
            + "                    \"motherName\": \"Ruth Hopkins\",\n"
            + "                    \"spouseId\": null,\n"
            + "                    \"spouseName\": null,\n"
            + "                    \"spouseGender\": null,\n"
            + "                    \"spouseLifeSpan\": null,\n"
            + "                    \"fatherLifeSpan\": null,\n"
            + "                    \"motherLifeSpan\": null\n"
            + "                }\n"
            + "            }\n"
            + "        ],\n"
            + "        \"sealingsToSpouses\": [\n"
            + "            {\n"
            + "                \"type\": \"SealingToSpouse\",\n"
            + "                \"status\": \"Completed\",\n"
            + "                \"whyNotQualifying\": [\n"
            + "                    \"This ordinance is completed.\"\n"
            + "                ],\n"
            + "                \"statusText\": \"Completed\",\n"
            + "                \"hoverText\": \"Sealing to Spouse completed at Salt Lake Temple on 7 January 1986.\",\n"
            + "                \"bornInCovenant\": false,\n"
            + "                \"owner\": null,\n"
            + "                \"ownerName\": null,\n"
            + "                \"assignedToTemple\": false,\n"
            + "                \"canAssign\": false,\n"
            + "                \"canTransfer\": false,\n"
            + "                \"canUnreserve\": false,\n"
            + "                \"reserve\": false,\n"
            + "                \"canPrint\": false,\n"
            + "                \"reservedDate\": null,\n"
            + "                \"comparableReservedDate\": null,\n"
            + "                \"lastModifiedDate\": null,\n"
            + "                \"comparableLastModifiedDate\": null,\n"
            + "                \"completedDate\": \"7 January 1986\",\n"
            + "                \"completedPlace\": \"Salt Lake Temple\",\n"
            + "                \"relationships\": {\n"
            + "                    \"fatherId\": null,\n"
            + "                    \"fatherName\": null,\n"
            + "                    \"motherId\": null,\n"
            + "                    \"motherName\": null,\n"
            + "                    \"spouseId\": \"KCPJ-2T9\",\n"
            + "                    \"spouseName\": \"Hannah A. Summers\",\n"
            + "                    \"spouseGender\": \"Female\",\n"
            + "                    \"spouseLifeSpan\": null,\n"
            + "                    \"fatherLifeSpan\": null,\n"
            + "                    \"motherLifeSpan\": null\n"
            + "                }\n"
            + "            },\n"
            + "            {\n"
            + "                \"type\": \"SealingToSpouse\",\n"
            + "                \"status\": \"Completed\",\n"
            + "                \"whyNotQualifying\": [\n"
            + "                    \"This ordinance is completed.\"\n"
            + "                ],\n"
            + "                \"statusText\": \"Completed\",\n"
            + "                \"hoverText\": \"Sealing to Spouse completed at Chicago Illinois Temple on 14 July 1995.\",\n"
            + "                \"bornInCovenant\": false,\n"
            + "                \"owner\": null,\n"
            + "                \"ownerName\": null,\n"
            + "                \"assignedToTemple\": false,\n"
            + "                \"canAssign\": false,\n"
            + "                \"canTransfer\": false,\n"
            + "                \"canUnreserve\": false,\n"
            + "                \"reserve\": false,\n"
            + "                \"canPrint\": false,\n"
            + "                \"reservedDate\": null,\n"
            + "                \"comparableReservedDate\": null,\n"
            + "                \"lastModifiedDate\": null,\n"
            + "                \"comparableLastModifiedDate\": null,\n"
            + "                \"completedDate\": \"14 July 1995\",\n"
            + "                \"completedPlace\": \"Chicago Illinois Temple\",\n"
            + "                \"relationships\": {\n"
            + "                    \"fatherId\": null,\n"
            + "                    \"fatherName\": null,\n"
            + "                    \"motherId\": null,\n"
            + "                    \"motherName\": null,\n"
            + "                    \"spouseId\": \"KGCQ-87V\",\n"
            + "                    \"spouseName\": \"Mary Forney\",\n"
            + "                    \"spouseGender\": \"Female\",\n"
            + "                    \"spouseLifeSpan\": null,\n"
            + "                    \"fatherLifeSpan\": null,\n"
            + "                    \"motherLifeSpan\": null\n"
            + "                }\n"
            + "            }\n"
            + "        ],\n"
            + "        \"hasPossibleDuplicates\": null\n"
            + "    },\n"
            + "    \"statuses\": null\n"
            + "}";

    private static Gson GSON = new Gson();
    
    @Test
    public void testFromJson() {
        PersonTemple pt = GSON.fromJson(responseWithReadyOrdinances, PersonTempleResponse.class).data;
        assertTrue(pt.hasOrdinancesReady());
        
        pt = GSON.fromJson(responseWithClaimedOrdinances, PersonTempleResponse.class).data;
        assertFalse(pt.hasOrdinancesReady());
        
        pt = GSON .fromJson(responseWithCompletedOrdinances, PersonTempleResponse.class).data;
        assertFalse(pt.hasOrdinancesReady());
        
        pt = GSON .fromJson(responseWithRequiresPermission, PersonTempleResponse.class).data;
        assertFalse(pt.hasOrdinancesReady());
    }

}
